spring.application.name=user-account-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/souq99_user_account_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*

#JWT CONFIG
jwt.secret=E^P;xdrR?(w~L+iFpvDCTY&Edj!2.a#<]0*XK_D*!BV"JnPv\}YXJev4)6f1XM]2Z
#I day expiration in millisec
jwt.expiration=86400000

#kafka config
spring.kafka.bootstrap-servers=localhost:9092

#Kafka Config as a Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type=true

spring.data.web.pageable.one-indexed-parameters=true

login.link=http://localhost:4200/login
verify.link=http://localhost:4200/verify
password.reset.link=http://localhost:4200/reset-password?code=

recaptcha.secret=6Le0Ss8sAAAAAG6eS-HxoguwNv4XjQFwRN9qtHiv
recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify