package com.souq99.useraccountservice.domain.value;

import lombok.Getter;

@Getter
public enum SubCategory {
    ABARTH(Category.VEHICLES, "enum.subcategory.abarth"),
    ACURA(Category.VEHICLES, "enum.subcategory.acura"),
    ALFA_ROMEO(Category.VEHICLES, "enum.subcategory.alfa_romeo"),
    ALPINE(Category.VEHICLES, "enum.subcategory.alpine"),
    AMC(Category.VEHICLES, "enum.subcategory.amc"),
    ARC_FOX(Category.VEHICLES, "enum.subcategory.arc_fox"),
    ASTON_MARTIN(Category.VEHICLES, "enum.subcategory.aston_martin"),
    AUDI(Category.VEHICLES, "enum.subcategory.audi"),
    BENTLEY(Category.VEHICLES, "enum.subcategory.bentley"),
    BMW(Category.VEHICLES, "enum.subcategory.bmw"),
    BUGATTI(Category.VEHICLES, "enum.subcategory.bugatti"),
    BUICK(Category.VEHICLES, "enum.subcategory.buick"),
    BYD(Category.VEHICLES, "enum.subcategory.byd"),
    CADILLAC(Category.VEHICLES, "enum.subcategory.cadillac"),
    CATERHAM(Category.VEHICLES, "enum.subcategory.caterham"),
    CHANGAN(Category.VEHICLES, "enum.subcategory.changan"),
    CHERY(Category.VEHICLES, "enum.subcategory.chery"),
    CHEVROLET(Category.VEHICLES, "enum.subcategory.chevrolet"),
    CHRYSLER(Category.VEHICLES, "enum.subcategory.chrysler"),
    CITROEN(Category.VEHICLES, "enum.subcategory.citroen"),
    CUPRA(Category.VEHICLES, "enum.subcategory.cupra"),
    DACIA(Category.VEHICLES, "enum.subcategory.dacia"),
    DAEWOO(Category.VEHICLES, "enum.subcategory.daewoo"),
    DAIHATSU(Category.VEHICLES, "enum.subcategory.daihatsu"),
    DODGE(Category.VEHICLES, "enum.subcategory.dodge"),
    DONGFENG(Category.VEHICLES, "enum.subcategory.dongfeng"),
    DS(Category.VEHICLES, "enum.subcategory.ds"),
    FERRARI(Category.VEHICLES, "enum.subcategory.ferrari"),
    FIAT(Category.VEHICLES, "enum.subcategory.fiat"),
    FISKER(Category.VEHICLES, "enum.subcategory.fisker"),
    FORD(Category.VEHICLES, "enum.subcategory.ford"),
    GEELY(Category.VEHICLES, "enum.subcategory.geely"),
    GENESIS(Category.VEHICLES, "enum.subcategory.genesis"),
    GMC(Category.VEHICLES, "enum.subcategory.gmc"),
    GREAT_WALL(Category.VEHICLES, "enum.subcategory.great_wall"),
    HAVAL(Category.VEHICLES, "enum.subcategory.haval"),
    HOLDEN(Category.VEHICLES, "enum.subcategory.holden"),
    HONDA(Category.VEHICLES, "enum.subcategory.honda"),
    HUMMER(Category.VEHICLES, "enum.subcategory.hummer"),
    HYUNDAI(Category.VEHICLES, "enum.subcategory.hyundai"),
    INFINITI(Category.VEHICLES, "enum.subcategory.infiniti"),
    ISUZU(Category.VEHICLES, "enum.subcategory.isuzu"),
    JAC(Category.VEHICLES, "enum.subcategory.jac"),
    JAGUAR(Category.VEHICLES, "enum.subcategory.jaguar"),
    JEEP(Category.VEHICLES, "enum.subcategory.jeep"),
    KIA(Category.VEHICLES, "enum.subcategory.kia"),
    KOENIGSEGG(Category.VEHICLES, "enum.subcategory.koenigsegg"),
    LADA(Category.VEHICLES, "enum.subcategory.lada"),
    LAMBORGHINI(Category.VEHICLES, "enum.subcategory.lamborghini"),
    LANCIA(Category.VEHICLES, "enum.subcategory.lancia"),
    LAND_ROVER(Category.VEHICLES, "enum.subcategory.land_rover"),
    LEXUS(Category.VEHICLES, "enum.subcategory.lexus"),
    LINCOLN(Category.VEHICLES, "enum.subcategory.lincoln"),
    LOTUS(Category.VEHICLES, "enum.subcategory.lotus"),
    LUCID(Category.VEHICLES, "enum.subcategory.lucid"),
    MASERATI(Category.VEHICLES, "enum.subcategory.maserati"),
    MAYBACH(Category.VEHICLES, "enum.subcategory.maybach"),
    MAZDA(Category.VEHICLES, "enum.subcategory.mazda"),
    MCLAREN(Category.VEHICLES, "enum.subcategory.mclaren"),
    MERCEDES_BENZ(Category.VEHICLES, "enum.subcategory.mercedes_benz"),
    MINI(Category.VEHICLES, "enum.subcategory.mini"),
    MITSUBISHI(Category.VEHICLES, "enum.subcategory.mitsubishi"),
    MORGAN(Category.VEHICLES, "enum.subcategory.morgan"),
    NIO(Category.VEHICLES, "enum.subcategory.nio"),
    NISSAN(Category.VEHICLES, "enum.subcategory.nissan"),
    OLDSMOBILE(Category.VEHICLES, "enum.subcategory.oldsmobile"),
    OPEL(Category.VEHICLES, "enum.subcategory.opel"),
    PAGANI(Category.VEHICLES, "enum.subcategory.pagani"),
    PEUGEOT(Category.VEHICLES, "enum.subcategory.peugeot"),
    PININFARINA(Category.VEHICLES, "enum.subcategory.pininfarina"),
    PLYMOUTH(Category.VEHICLES, "enum.subcategory.plymouth"),
    POLESTAR(Category.VEHICLES, "enum.subcategory.polestar"),
    PONTIAC(Category.VEHICLES, "enum.subcategory.pontiac"),
    PORSCHE(Category.VEHICLES, "enum.subcategory.porsche"),
    PROTON(Category.VEHICLES, "enum.subcategory.proton"),
    RAM(Category.VEHICLES, "enum.subcategory.ram"),
    RENAULT(Category.VEHICLES, "enum.subcategory.renault"),
    RIMAC(Category.VEHICLES, "enum.subcategory.rimac"),
    RIVIAN(Category.VEHICLES, "enum.subcategory.rivian"),
    ROLLS_ROYCE(Category.VEHICLES, "enum.subcategory.rolls_royce"),
    ROVER(Category.VEHICLES, "enum.subcategory.rover"),
    SAAB(Category.VEHICLES, "enum.subcategory.saab"),
    SEAT(Category.VEHICLES, "enum.subcategory.seat"),
    SKODA(Category.VEHICLES, "enum.subcategory.skoda"),
    SMART(Category.VEHICLES, "enum.subcategory.smart"),
    SSANGYONG(Category.VEHICLES, "enum.subcategory.ssangyong"),
    SUBARU(Category.VEHICLES, "enum.subcategory.subaru"),
    SUZUKI(Category.VEHICLES, "enum.subcategory.suzuki"),
    TATA(Category.VEHICLES, "enum.subcategory.tata"),
    TESLA(Category.VEHICLES, "enum.subcategory.tesla"),
    TOYOTA(Category.VEHICLES, "enum.subcategory.toyota"),
    TRIUMPH(Category.VEHICLES, "enum.subcategory.triumph"),
    TVR(Category.VEHICLES, "enum.subcategory.tvr"),
    VAUXHALL(Category.VEHICLES, "enum.subcategory.vauxhall"),
    VINFAST(Category.VEHICLES, "enum.subcategory.vinfast"),
    VOLKSWAGEN(Category.VEHICLES, "enum.subcategory.volkswagen"),
    VOLVO(Category.VEHICLES, "enum.subcategory.volvo"),
    XPENG(Category.VEHICLES, "enum.subcategory.xpeng"),
    ZEEKR(Category.VEHICLES, "enum.subcategory.zeekr"),

    VEHICLES_FOR_RENT(Category.VEHICLES, "enum.subcategory.vehicles_for_rent"),
    MOTORCYCLE_AND_ACCESSORIES(Category.VEHICLES, "enum.subcategory.motorcycle_and_accessories"),
    HEAVY_MACHINERY(Category.VEHICLES, "enum.subcategory.heavy_machinery"),
    BUSES_TRUCKS_TRAILERS(Category.VEHICLES, "enum.subcategory.buses_trucks_trailers"),
    BOATS_AND_JETSKIS(Category.VEHICLES, "enum.subcategory.boats_and_jetskis"),
    SPECIAL_PLATE_NUMBER(Category.VEHICLES, "enum.subcategory.special_plate_number"),
    AUTO_WHEELS_AND_TIRES(Category.VEHICLES, "enum.subcategory.auto_wheels_and_tires"),
    VEHICLE_SPARE_PART(Category.VEHICLES, "enum.subcategory.vehicle_spare_part"),
    VEHICLE_ACCESSORIES(Category.VEHICLES, "enum.subcategory.vehicle_accessories"),

    MOBILE(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.mobile"),
    TABLET(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.tablet"),
    LAPTOP_AND_COMPUTER(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.laptop_and_computer"),
    DIGITAL_CAMERA(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.digital_camera"),
    ELECTRONICS(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.electronics"),
    HOME_APPLIANCES(Category.ELECTRONICS_AND_HOME_APPLIANCES, "enum.subcategory.home_appliances"),

    APARTMENT_FOR_RENT(Category.HOUSING, "enum.subcategory.apartment_for_rent"),
    LAND_FOR_SALE(Category.HOUSING, "enum.subcategory.land_for_sale"),
    VILLAS_FOR_SALE(Category.HOUSING, "enum.subcategory.villas_for_sale"),
    APARTMENT_FOR_SALE(Category.HOUSING, "enum.subcategory.apartment_for_sale"),
    HOUSES_FOR_SALE(Category.HOUSING, "enum.subcategory.houses_for_sale"),
    COMMERCIAL_LAND_FOR_SALE(Category.HOUSING, "enum.subcategory.commercial_land_for_sale"),
    BUILDING_FOR_SALE(Category.HOUSING, "enum.subcategory.building_for_sale"),
    SHOPS_FOR_SALE(Category.HOUSING, "enum.subcategory.shops_for_sale"),
    SHOPS_FOR_RENT(Category.HOUSING, "enum.subcategory.shops_for_rent"),
    BUILDING_FOR_RENT(Category.HOUSING, "enum.subcategory.building_for_rent"),
    VILLAS_FOR_RENT(Category.HOUSING, "enum.subcategory.villas_for_rent"),
    FARMS_FOR_SALE(Category.HOUSING, "enum.subcategory.farms_for_sale"),
    HOUSES_FOR_RENT(Category.HOUSING, "enum.subcategory.houses_for_rent"),
    ROOMS_FOR_RENT(Category.HOUSING, "enum.subcategory.rooms_for_rent"),
    CAMPS_FOR_RENT(Category.HOUSING, "enum.subcategory.camps_for_rent"),
    FARM_FOR_RENT(Category.HOUSING, "enum.subcategory.farm_for_rent"),
    WAREHOUSE_FOR_RENT(Category.HOUSING, "enum.subcategory.warehouse_for_rent"),
    WAREHOUSE_FOR_SALE(Category.HOUSING, "enum.subcategory.warehouse_for_sale"),
    OFFICE_FOR_RENT(Category.HOUSING, "enum.subcategory.office_for_rent"),

    KITCHENWARE_AND_DISHES(Category.HOME_AND_GARDEN, "enum.subcategory.kitchenware_and_dishes"),
    HOME_DECOR_AND_ACCESSORIES(Category.HOME_AND_GARDEN, "enum.subcategory.home_decor_and_accessories"),
    OTHER_HOME_AND_GARDEN(Category.HOME_AND_GARDEN, "enum.subcategory.other_home_and_garden"),
    FURNITURE(Category.HOME_AND_GARDEN, "enum.subcategory.furniture"),
    BATHROOMS_AND_ACCESSORIES(Category.HOME_AND_GARDEN, "enum.subcategory.bathrooms_and_accessories"),
    POOLS_AND_SAUNA(Category.HOME_AND_GARDEN, "enum.subcategory.pools_and_sauna"),
    OUTDOOR_AND_GARDEN_FURNITURE(Category.HOME_AND_GARDEN, "enum.subcategory.outdoor_and_garden_furniture"),
    PLANTS(Category.HOME_AND_GARDEN, "enum.subcategory.plants"),
    LIGHTING(Category.HOME_AND_GARDEN, "enum.subcategory.lighting"),
    DOORS_WINDOWS_AND_GATES(Category.HOME_AND_GARDEN, "enum.subcategory.doors_windows_and_gates"),
    TILES_AND_FLOORING(Category.HOME_AND_GARDEN, "enum.subcategory.tiles_and_flooring"),

    WOMAN(Category.FASHION_AND_KIDS, "enum.subcategory.woman"),
    MAN(Category.FASHION_AND_KIDS, "enum.subcategory.man"),
    KIDS(Category.FASHION_AND_KIDS, "enum.subcategory.kids"),

    MAKEUP(Category.BEAUTY_AND_HEALTH, "enum.subcategory.makeup"),
    NAIL_SUPPLIES(Category.BEAUTY_AND_HEALTH, "enum.subcategory.nail_supplies"),
    COSMETICS(Category.BEAUTY_AND_HEALTH, "enum.subcategory.cosmetics"),
    PERFUMES(Category.BEAUTY_AND_HEALTH, "enum.subcategory.perfumes"),

    OILS(Category.FOOD_AND_GROCERIES, "enum.subcategory.oils"),
    DATES(Category.FOOD_AND_GROCERIES, "enum.subcategory.dates"),
    HONEY(Category.FOOD_AND_GROCERIES, "enum.subcategory.honey"),
    READY_MEALS(Category.FOOD_AND_GROCERIES, "enum.subcategory.ready_meals"),
    SWEETS(Category.FOOD_AND_GROCERIES, "enum.subcategory.sweets"),
    VITAMINS_AND_SUPPLEMENTS(Category.FOOD_AND_GROCERIES, "enum.subcategory.vitamins_and_supplements"),
    CHEESE(Category.FOOD_AND_GROCERIES, "enum.subcategory.cheese"),
    VEGETABLES_AND_FRUITS(Category.FOOD_AND_GROCERIES, "enum.subcategory.vegetables_and_fruits"),
    MEAT(Category.FOOD_AND_GROCERIES, "enum.subcategory.meat"),
    OTHER_FOOD(Category.FOOD_AND_GROCERIES, "enum.subcategory.other_food"),

    BUSINESS_SERVICES(Category.SERVICES, "enum.subcategory.business_services"),
    HEALTH_AND_BEAUTY(Category.SERVICES, "enum.subcategory.health_and_beauty"),
    CONSTRUCTION_AND_CONTRACTING(Category.SERVICES, "enum.subcategory.construction_and_contracting"),
    MOVING_AND_DELIVERY(Category.SERVICES, "enum.subcategory.moving_and_delivery"),
    CLEANING_AND_LAUNDRY(Category.SERVICES, "enum.subcategory.cleaning_and_laundry"),
    MAINTENANCE_AND_HANDYMAN(Category.SERVICES, "enum.subcategory.maintenance_and_handyman"),
    LANDSCAPING_AND_GARDEN_CARE(Category.SERVICES, "enum.subcategory.landscaping_and_garden_care"),
    VEHICLE_SERVICES(Category.SERVICES, "enum.subcategory.vehicle_services"),
    ELECTRONICS_AND_APPLIANCE_REPAIR(Category.SERVICES, "enum.subcategory.electronics_and_appliance_repair"),
    HOUSEHOLD_AND_CHILDCARE(Category.SERVICES, "enum.subcategory.household_and_childcare"),
    PET_CARE(Category.SERVICES, "enum.subcategory.pet_care"),
    EVENTS_AND_OCCASIONS(Category.SERVICES, "enum.subcategory.events_and_occasions"),
    TEACHING_AND_TRAINING(Category.SERVICES, "enum.subcategory.teaching_and_training"),

    JOB_SEEKERS(Category.JOBS, "enum.subcategory.job_seekers"),
    JOB_VACANCY(Category.JOBS, "enum.subcategory.job_vacancy"),

    PET(Category.PETS_AND_ACCESSORIES, "enum.subcategory.pet"),
    PET_FOOD(Category.PETS_AND_ACCESSORIES, "enum.subcategory.pet_food"),
    PET_ACCESSORIES(Category.PETS_AND_ACCESSORIES, "enum.subcategory.pet_accessories"),

    BOOKS(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.books"),
    TICKETS(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.tickets"),
    COUPONS_AND_VOUCHERS(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.coupons_and_vouchers"),
    MAGAZINES(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.magazines"),
    COLLECTIBLES(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.collectibles"),
    MUSICAL_INSTRUMENTS_AND_ACCESSORIES(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.musical_instruments_and_accessories"),
    ARTS_AND_CRAFTS(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.arts_and_crafts"),
    STATIONERY(Category.ENTERTAINMENT_BOOKS_AND_COLLECTIONS, "enum.subcategory.stationery"),

    BICYCLES_AND_ACCESSORIES(Category.SPORTS_AND_FITNESS, "enum.subcategory.bicycles_and_accessories"),
    FITNESS_AND_GYM_EQUIPMENT(Category.SPORTS_AND_FITNESS, "enum.subcategory.fitness_and_gym_equipment"),
    RACKET_AND_TABLE_SPORTS(Category.SPORTS_AND_FITNESS, "enum.subcategory.racket_and_table_sports"),
    SKATEBOARDS(Category.SPORTS_AND_FITNESS, "enum.subcategory.skateboards"),
    SPORTS_ACCESSORIES(Category.SPORTS_AND_FITNESS, "enum.subcategory.sports_accessories"),
    CAMPING_AND_HIKING(Category.SPORTS_AND_FITNESS, "enum.subcategory.camping_and_hiking"),
    HUNTING_AND_SHOOTING(Category.SPORTS_AND_FITNESS, "enum.subcategory.hunting_and_shooting"),
    MARTIAL_ARTS(Category.SPORTS_AND_FITNESS, "enum.subcategory.martial_arts"),
    DIVING_AND_WATER_SPORTS(Category.SPORTS_AND_FITNESS, "enum.subcategory.diving_and_water_sports"),
    BALL_SPORTS(Category.SPORTS_AND_FITNESS, "enum.subcategory.ball_sports"),

    READY_PROJECTS_AND_INVESTMENT(Category.BUSINESS_AND_EQUIPMENT, "enum.subcategory.ready_projects_and_investment"),
    BUSINESS_EQUIPMENT(Category.BUSINESS_AND_EQUIPMENT, "enum.subcategory.business_equipment");

    private final Category category;
    private final String messageKey;

    SubCategory(Category category, String messageKey) {
        this.category = category;
        this.messageKey = messageKey;
    }
}
